// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: concurrency.sql

package sqlcv2

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkStrategyActive = `-- name: CheckStrategyActive :one
WITH workflow AS (
    SELECT
        w."id" as "id",
        wv."id" as "workflowVersionId",
        w."tenantId" as "tenantId"
    FROM
        "Step" s
    JOIN
        "Job" j ON j."id" = s."jobId"
    JOIN
        "WorkflowVersion" wv ON wv."id" = j."workflowVersionId"
    JOIN
        "Workflow" w ON w."id" = wv."workflowId"
    WHERE
        s."id" = $1::uuid
        AND w."tenantId" = $2::uuid
        AND w."deletedAt" IS NULL
        AND wv."deletedAt" IS NULL
), latest_workflow_version AS (
    SELECT DISTINCT ON("workflowId")
        "workflowId",
        workflowVersions."id" AS "workflowVersionId"
    FROM
        "WorkflowVersion" as workflowVersions
    JOIN
        workflow ON workflow."id" = workflowVersions."workflowId"
    WHERE
        workflow."tenantId" = $2::uuid
        AND workflowVersions."deletedAt" IS NULL
    ORDER BY "workflowId", "order" DESC
    LIMIT 1
), active_slot AS (
    SELECT
        task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at
    FROM
        v2_concurrency_slot
    WHERE
        tenant_id = $2::uuid AND
        strategy_id = $3::bigint
        -- Note we don't check for is_filled=False, because is_filled=True could imply that the task
        -- gets retried and the slot is still active.
    LIMIT 1
), is_active AS (
    SELECT
        EXISTS(SELECT 1 FROM workflow) AND
        (
            workflow."workflowVersionId" = latest_workflow_version."workflowVersionId" OR
            EXISTS(SELECT 1 FROM active_slot)
        ) AS "isActive"
    FROM
        workflow, latest_workflow_version
)
SELECT COALESCE((SELECT "isActive" FROM is_active), FALSE)::bool AS "isActive"
`

type CheckStrategyActiveParams struct {
	Stepid     pgtype.UUID `json:"stepid"`
	Tenantid   pgtype.UUID `json:"tenantid"`
	Strategyid int64       `json:"strategyid"`
}

// A strategy is active if the workflow is not deleted, and it is attached to the latest workflow version or it has
// at least one concurrency slot that is not filled.
func (q *Queries) CheckStrategyActive(ctx context.Context, db DBTX, arg CheckStrategyActiveParams) (bool, error) {
	row := db.QueryRow(ctx, checkStrategyActive, arg.Stepid, arg.Tenantid, arg.Strategyid)
	var isActive bool
	err := row.Scan(&isActive)
	return isActive, err
}

const concurrencyAdvisoryLock = `-- name: ConcurrencyAdvisoryLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

func (q *Queries) ConcurrencyAdvisoryLock(ctx context.Context, db DBTX, key int64) error {
	_, err := db.Exec(ctx, concurrencyAdvisoryLock, key)
	return err
}

const listActiveConcurrencyStrategies = `-- name: ListActiveConcurrencyStrategies :many
SELECT
    id, workflow_id, step_id, is_active, strategy, expression, tenant_id, max_concurrency
FROM
    v2_step_concurrency
WHERE
    tenant_id = $1::uuid AND
    is_active = TRUE
`

func (q *Queries) ListActiveConcurrencyStrategies(ctx context.Context, db DBTX, tenantid pgtype.UUID) ([]*V2StepConcurrency, error) {
	rows, err := db.Query(ctx, listActiveConcurrencyStrategies, tenantid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*V2StepConcurrency
	for rows.Next() {
		var i V2StepConcurrency
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.StepID,
			&i.IsActive,
			&i.Strategy,
			&i.Expression,
			&i.TenantID,
			&i.MaxConcurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConcurrencyStrategiesByStepId = `-- name: ListConcurrencyStrategiesByStepId :many
SELECT
    id, workflow_id, step_id, is_active, strategy, expression, tenant_id, max_concurrency
FROM
    v2_step_concurrency
WHERE
    tenant_id = $1::uuid AND
    step_id = ANY($2::uuid[])
ORDER BY 
    id ASC
`

type ListConcurrencyStrategiesByStepIdParams struct {
	Tenantid pgtype.UUID   `json:"tenantid"`
	Stepids  []pgtype.UUID `json:"stepids"`
}

func (q *Queries) ListConcurrencyStrategiesByStepId(ctx context.Context, db DBTX, arg ListConcurrencyStrategiesByStepIdParams) ([]*V2StepConcurrency, error) {
	rows, err := db.Query(ctx, listConcurrencyStrategiesByStepId, arg.Tenantid, arg.Stepids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*V2StepConcurrency
	for rows.Next() {
		var i V2StepConcurrency
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.StepID,
			&i.IsActive,
			&i.Strategy,
			&i.Expression,
			&i.TenantID,
			&i.MaxConcurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runCancelInProgress = `-- name: RunCancelInProgress :many
WITH slots AS (
    SELECT 
        task_id,
        task_inserted_at,
        task_retry_count,
        tenant_id,
        strategy_id,
        key,
        is_filled,
        -- Order slots by rn desc, seqnum desc to ensure that the most recent tasks will be run
        row_number() OVER (PARTITION BY key ORDER BY task_id DESC, task_inserted_at DESC) AS rn,
        row_number() OVER (ORDER BY task_id DESC, task_inserted_at DESC) AS seqnum
    FROM    
        v2_concurrency_slot
    WHERE
        tenant_id = $1::uuid AND
        strategy_id = $2::bigint AND
        schedule_timeout_at >= NOW()
), schedule_timeout_slots AS (
    SELECT
        task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at
    FROM
        v2_concurrency_slot
    WHERE
        tenant_id = $1::uuid AND
        strategy_id = $2::bigint AND
        schedule_timeout_at < NOW() AND
        is_filled = FALSE
), eligible_running_slots AS (
    SELECT
        task_id,
        task_inserted_at,
        task_retry_count,
        tenant_id,
        strategy_id,
        key,
        is_filled,
        rn,
        seqnum
    FROM
        slots
    WHERE
        rn <= $3::int
), slots_to_cancel AS (
    SELECT
        task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at
    FROM
        v2_concurrency_slot
    WHERE
        tenant_id = $1::uuid AND
        strategy_id = $2::bigint AND
        (task_inserted_at, task_id, task_retry_count) NOT IN (
            SELECT
                ers.task_inserted_at,
                ers.task_id,
                ers.task_retry_count
            FROM
                eligible_running_slots ers
        )
    ORDER BY
        task_id, task_inserted_at
    FOR UPDATE
), slots_to_run AS (
    SELECT
        task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at
    FROM
        v2_concurrency_slot
    WHERE 
        (task_inserted_at, task_id, task_retry_count, tenant_id, strategy_id) IN (
            SELECT
                ers.task_inserted_at,
                ers.task_id,
                ers.task_retry_count,
                ers.tenant_id,
                ers.strategy_id
            FROM
                eligible_running_slots ers
            ORDER BY
                rn, seqnum
        )
    ORDER BY
        task_id, task_inserted_at
    FOR UPDATE
), updated_slots AS (
    UPDATE
        v2_concurrency_slot
    SET
        is_filled = TRUE
    FROM
        slots_to_run
    WHERE
        v2_concurrency_slot.task_id = slots_to_run.task_id AND
        v2_concurrency_slot.task_inserted_at = slots_to_run.task_inserted_at AND
        v2_concurrency_slot.task_retry_count = slots_to_run.task_retry_count AND
        v2_concurrency_slot.key = slots_to_run.key AND
        v2_concurrency_slot.is_filled = FALSE
    RETURNING
        v2_concurrency_slot.task_id, v2_concurrency_slot.task_inserted_at, v2_concurrency_slot.task_retry_count, v2_concurrency_slot.tenant_id, v2_concurrency_slot.workflow_id, v2_concurrency_slot.strategy_id, v2_concurrency_slot.priority, v2_concurrency_slot.key, v2_concurrency_slot.is_filled, v2_concurrency_slot.next_strategy_ids, v2_concurrency_slot.next_keys, v2_concurrency_slot.queue_to_notify, v2_concurrency_slot.schedule_timeout_at
), deleted_slots AS (
    DELETE FROM
        v2_concurrency_slot
    WHERE
        (task_inserted_at, task_id, task_retry_count) IN (
            SELECT
                c.task_inserted_at,
                c.task_id,
                c.task_retry_count
            FROM
                slots_to_cancel c
        )
)
SELECT
    task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at,
    'SCHEDULING_TIMED_OUT' AS "operation"
FROM
    schedule_timeout_slots
UNION ALL
SELECT
    task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at,
    'CANCELLED' AS "operation"
FROM    
    slots_to_cancel
WHERE
    -- not in the schedule_timeout_slots
    (task_inserted_at, task_id, task_retry_count) NOT IN (
        SELECT
            c.task_inserted_at,
            c.task_id,
            c.task_retry_count
        FROM
            schedule_timeout_slots c
    )
UNION ALL
SELECT
    task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at,
    'RUNNING' AS "operation"
FROM
    updated_slots
`

type RunCancelInProgressParams struct {
	Tenantid   pgtype.UUID `json:"tenantid"`
	Strategyid int64       `json:"strategyid"`
	Maxruns    int32       `json:"maxruns"`
}

type RunCancelInProgressRow struct {
	TaskID            int64              `json:"task_id"`
	TaskInsertedAt    pgtype.Timestamptz `json:"task_inserted_at"`
	TaskRetryCount    int32              `json:"task_retry_count"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	WorkflowID        pgtype.UUID        `json:"workflow_id"`
	StrategyID        int64              `json:"strategy_id"`
	Priority          int32              `json:"priority"`
	Key               string             `json:"key"`
	IsFilled          bool               `json:"is_filled"`
	NextStrategyIds   []int64            `json:"next_strategy_ids"`
	NextKeys          []string           `json:"next_keys"`
	QueueToNotify     string             `json:"queue_to_notify"`
	ScheduleTimeoutAt pgtype.Timestamp   `json:"schedule_timeout_at"`
	Operation         string             `json:"operation"`
}

func (q *Queries) RunCancelInProgress(ctx context.Context, db DBTX, arg RunCancelInProgressParams) ([]*RunCancelInProgressRow, error) {
	rows, err := db.Query(ctx, runCancelInProgress, arg.Tenantid, arg.Strategyid, arg.Maxruns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunCancelInProgressRow
	for rows.Next() {
		var i RunCancelInProgressRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskInsertedAt,
			&i.TaskRetryCount,
			&i.TenantID,
			&i.WorkflowID,
			&i.StrategyID,
			&i.Priority,
			&i.Key,
			&i.IsFilled,
			&i.NextStrategyIds,
			&i.NextKeys,
			&i.QueueToNotify,
			&i.ScheduleTimeoutAt,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runCancelNewest = `-- name: RunCancelNewest :many
WITH slots AS (
    SELECT 
        task_id,
        task_inserted_at,
        task_retry_count,
        tenant_id,
        strategy_id,
        key,
        is_filled,
        row_number() OVER (PARTITION BY key ORDER BY task_id ASC, task_inserted_at ASC) AS rn,
        row_number() OVER (ORDER BY task_id ASC, task_inserted_at ASC) AS seqnum
    FROM    
        v2_concurrency_slot
    WHERE
        tenant_id = $1::uuid AND
        strategy_id = $2::bigint AND
        schedule_timeout_at >= NOW()
), schedule_timeout_slots AS (
    SELECT
        task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at
    FROM
        v2_concurrency_slot
    WHERE
        tenant_id = $1::uuid AND
        strategy_id = $2::bigint AND
        schedule_timeout_at < NOW() AND
        is_filled = FALSE
), eligible_running_slots AS (
    SELECT
        task_id,
        task_inserted_at,
        task_retry_count,
        tenant_id,
        strategy_id,
        key,
        is_filled,
        rn,
        seqnum
    FROM
        slots
    WHERE
        rn <= $3::int
), slots_to_cancel AS (
    SELECT
        task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at
    FROM
        v2_concurrency_slot
    WHERE
        tenant_id = $1::uuid AND
        strategy_id = $2::bigint AND
        (task_inserted_at, task_id, task_retry_count) NOT IN (
            SELECT
                ers.task_inserted_at,
                ers.task_id,
                ers.task_retry_count
            FROM
                eligible_running_slots ers
        )
    ORDER BY
        task_id ASC, task_inserted_at ASC
    FOR UPDATE
), slots_to_run AS (
    SELECT
        task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at
    FROM
        v2_concurrency_slot
    WHERE 
        (task_inserted_at, task_id, task_retry_count, tenant_id, strategy_id) IN (
            SELECT
                ers.task_inserted_at,
                ers.task_id,
                ers.task_retry_count,
                ers.tenant_id,
                ers.strategy_id
            FROM
                eligible_running_slots ers
            ORDER BY
                rn, seqnum
        )
    ORDER BY
        task_id ASC, task_inserted_at ASC
    FOR UPDATE
), updated_slots AS (
    UPDATE
        v2_concurrency_slot
    SET
        is_filled = TRUE
    FROM
        slots_to_run
    WHERE
        v2_concurrency_slot.task_id = slots_to_run.task_id AND
        v2_concurrency_slot.task_inserted_at = slots_to_run.task_inserted_at AND
        v2_concurrency_slot.task_retry_count = slots_to_run.task_retry_count AND
        v2_concurrency_slot.key = slots_to_run.key AND
        v2_concurrency_slot.is_filled = FALSE
    RETURNING
        v2_concurrency_slot.task_id, v2_concurrency_slot.task_inserted_at, v2_concurrency_slot.task_retry_count, v2_concurrency_slot.tenant_id, v2_concurrency_slot.workflow_id, v2_concurrency_slot.strategy_id, v2_concurrency_slot.priority, v2_concurrency_slot.key, v2_concurrency_slot.is_filled, v2_concurrency_slot.next_strategy_ids, v2_concurrency_slot.next_keys, v2_concurrency_slot.queue_to_notify, v2_concurrency_slot.schedule_timeout_at
), deleted_slots AS (
    DELETE FROM
        v2_concurrency_slot
    WHERE
        (task_inserted_at, task_id, task_retry_count) IN (
            SELECT
                c.task_inserted_at,
                c.task_id,
                c.task_retry_count
            FROM
                slots_to_cancel c
        )
)
SELECT
    task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at,
    'SCHEDULING_TIMED_OUT' AS "operation"
FROM
    schedule_timeout_slots
UNION ALL
SELECT
    task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at,
    'CANCELLED' AS "operation"
FROM    
    slots_to_cancel
WHERE
    -- not in the schedule_timeout_slots
    (task_inserted_at, task_id, task_retry_count) NOT IN (
        SELECT
            c.task_inserted_at,
            c.task_id,
            c.task_retry_count
        FROM
            schedule_timeout_slots c
    )
UNION ALL
SELECT
    task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at,
    'RUNNING' AS "operation"
FROM
    updated_slots
`

type RunCancelNewestParams struct {
	Tenantid   pgtype.UUID `json:"tenantid"`
	Strategyid int64       `json:"strategyid"`
	Maxruns    int32       `json:"maxruns"`
}

type RunCancelNewestRow struct {
	TaskID            int64              `json:"task_id"`
	TaskInsertedAt    pgtype.Timestamptz `json:"task_inserted_at"`
	TaskRetryCount    int32              `json:"task_retry_count"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	WorkflowID        pgtype.UUID        `json:"workflow_id"`
	StrategyID        int64              `json:"strategy_id"`
	Priority          int32              `json:"priority"`
	Key               string             `json:"key"`
	IsFilled          bool               `json:"is_filled"`
	NextStrategyIds   []int64            `json:"next_strategy_ids"`
	NextKeys          []string           `json:"next_keys"`
	QueueToNotify     string             `json:"queue_to_notify"`
	ScheduleTimeoutAt pgtype.Timestamp   `json:"schedule_timeout_at"`
	Operation         string             `json:"operation"`
}

func (q *Queries) RunCancelNewest(ctx context.Context, db DBTX, arg RunCancelNewestParams) ([]*RunCancelNewestRow, error) {
	rows, err := db.Query(ctx, runCancelNewest, arg.Tenantid, arg.Strategyid, arg.Maxruns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunCancelNewestRow
	for rows.Next() {
		var i RunCancelNewestRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskInsertedAt,
			&i.TaskRetryCount,
			&i.TenantID,
			&i.WorkflowID,
			&i.StrategyID,
			&i.Priority,
			&i.Key,
			&i.IsFilled,
			&i.NextStrategyIds,
			&i.NextKeys,
			&i.QueueToNotify,
			&i.ScheduleTimeoutAt,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGroupRoundRobin = `-- name: RunGroupRoundRobin :many
WITH slots AS (
    SELECT 
        task_id,
        task_inserted_at,
        task_retry_count,
        key,
        strategy_id,
        tenant_id,
        is_filled,
        row_number() OVER (PARTITION BY key ORDER BY priority DESC, task_id ASC, task_inserted_at ASC) AS rn,
        row_number() OVER (ORDER BY priority DESC, task_id ASC, task_inserted_at ASC) AS seqnum
    FROM    
        v2_concurrency_slot
    WHERE
        tenant_id = $1::uuid AND
        strategy_id = $2::bigint AND
        schedule_timeout_at >= NOW()
), schedule_timeout_slots AS (
    SELECT
        task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at
    FROM
        v2_concurrency_slot
    WHERE
        tenant_id = $1::uuid AND
        strategy_id = $2::bigint AND
        schedule_timeout_at < NOW() AND
        is_filled = FALSE
    ORDER BY
        task_id, task_inserted_at
    FOR UPDATE
), eligible_slots_per_group AS (
    SELECT
        task_id,
        task_inserted_at,
        task_retry_count,
        tenant_id,
        strategy_id,
        key,
        is_filled,
        rn,
        seqnum
    FROM
        slots
    WHERE
        rn <= $3::int
), eligible_slots AS (
    SELECT
        task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at
    FROM
        v2_concurrency_slot
    WHERE 
        (task_inserted_at, task_id, task_retry_count, tenant_id, strategy_id) IN (
            SELECT
                es.task_inserted_at,
                es.task_id,
                es.task_retry_count,
                es.tenant_id,
                es.strategy_id
            FROM
                eligible_slots_per_group es
            ORDER BY
                rn, seqnum
            LIMIT ($3::int) * (SELECT COUNT(DISTINCT key) FROM slots)
        )
        AND is_filled = FALSE
    ORDER BY
        task_id, task_inserted_at
    FOR UPDATE
), updated_slots AS (
    UPDATE
        v2_concurrency_slot
    SET
        is_filled = TRUE
    FROM
        eligible_slots
    WHERE
        v2_concurrency_slot.task_id = eligible_slots.task_id AND
        v2_concurrency_slot.task_inserted_at = eligible_slots.task_inserted_at AND
        v2_concurrency_slot.task_retry_count = eligible_slots.task_retry_count AND
        v2_concurrency_slot.tenant_id = eligible_slots.tenant_id AND
        v2_concurrency_slot.strategy_id = eligible_slots.strategy_id AND
        v2_concurrency_slot.key = eligible_slots.key
    RETURNING
        v2_concurrency_slot.task_id, v2_concurrency_slot.task_inserted_at, v2_concurrency_slot.task_retry_count, v2_concurrency_slot.tenant_id, v2_concurrency_slot.workflow_id, v2_concurrency_slot.strategy_id, v2_concurrency_slot.priority, v2_concurrency_slot.key, v2_concurrency_slot.is_filled, v2_concurrency_slot.next_strategy_ids, v2_concurrency_slot.next_keys, v2_concurrency_slot.queue_to_notify, v2_concurrency_slot.schedule_timeout_at
), deleted_slots AS (
    DELETE FROM
        v2_concurrency_slot
    WHERE
        (task_inserted_at, task_id, task_retry_count) IN (
            SELECT
                c.task_inserted_at,
                c.task_id,
                c.task_retry_count
            FROM
                schedule_timeout_slots c
        )
)
SELECT
    task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at,
    'SCHEDULING_TIMED_OUT' AS "operation"
FROM
    schedule_timeout_slots
UNION ALL
SELECT
    task_id, task_inserted_at, task_retry_count, tenant_id, workflow_id, strategy_id, priority, key, is_filled, next_strategy_ids, next_keys, queue_to_notify, schedule_timeout_at,
    'RUNNING' AS "operation"
FROM
    updated_slots
`

type RunGroupRoundRobinParams struct {
	Tenantid   pgtype.UUID `json:"tenantid"`
	Strategyid int64       `json:"strategyid"`
	Maxruns    int32       `json:"maxruns"`
}

type RunGroupRoundRobinRow struct {
	TaskID            int64              `json:"task_id"`
	TaskInsertedAt    pgtype.Timestamptz `json:"task_inserted_at"`
	TaskRetryCount    int32              `json:"task_retry_count"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	WorkflowID        pgtype.UUID        `json:"workflow_id"`
	StrategyID        int64              `json:"strategy_id"`
	Priority          int32              `json:"priority"`
	Key               string             `json:"key"`
	IsFilled          bool               `json:"is_filled"`
	NextStrategyIds   []int64            `json:"next_strategy_ids"`
	NextKeys          []string           `json:"next_keys"`
	QueueToNotify     string             `json:"queue_to_notify"`
	ScheduleTimeoutAt pgtype.Timestamp   `json:"schedule_timeout_at"`
	Operation         string             `json:"operation"`
}

func (q *Queries) RunGroupRoundRobin(ctx context.Context, db DBTX, arg RunGroupRoundRobinParams) ([]*RunGroupRoundRobinRow, error) {
	rows, err := db.Query(ctx, runGroupRoundRobin, arg.Tenantid, arg.Strategyid, arg.Maxruns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RunGroupRoundRobinRow
	for rows.Next() {
		var i RunGroupRoundRobinRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskInsertedAt,
			&i.TaskRetryCount,
			&i.TenantID,
			&i.WorkflowID,
			&i.StrategyID,
			&i.Priority,
			&i.Key,
			&i.IsFilled,
			&i.NextStrategyIds,
			&i.NextKeys,
			&i.QueueToNotify,
			&i.ScheduleTimeoutAt,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConcurrencyStrategyInactive = `-- name: SetConcurrencyStrategyInactive :exec
UPDATE
    v2_step_concurrency
SET
    is_active = FALSE
WHERE
    workflow_id = $1::uuid AND
    step_id = $2::uuid AND
    id = $3::bigint
`

type SetConcurrencyStrategyInactiveParams struct {
	Workflowid pgtype.UUID `json:"workflowid"`
	Stepid     pgtype.UUID `json:"stepid"`
	Strategyid int64       `json:"strategyid"`
}

func (q *Queries) SetConcurrencyStrategyInactive(ctx context.Context, db DBTX, arg SetConcurrencyStrategyInactiveParams) error {
	_, err := db.Exec(ctx, setConcurrencyStrategyInactive, arg.Workflowid, arg.Stepid, arg.Strategyid)
	return err
}
